/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohamad
 */
public class Kalkulator extends javax.swing.JFrame {

    String angka;
    Double total, angka1, angka2;
    int pilih;

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd1 = new javax.swing.JButton();
        tampil = new javax.swing.JFormattedTextField();
        cmd2 = new javax.swing.JButton();
        cmdSamaDengan = new javax.swing.JButton();
        cmdTambah = new javax.swing.JButton();
        cmd3 = new javax.swing.JButton();
        cmd4 = new javax.swing.JButton();
        cmd5 = new javax.swing.JButton();
        cmd6 = new javax.swing.JButton();
        cmd7 = new javax.swing.JButton();
        cmd8 = new javax.swing.JButton();
        cmd9 = new javax.swing.JButton();
        cmd0 = new javax.swing.JButton();
        cmdKoma = new javax.swing.JButton();
        cmdKurang = new javax.swing.JButton();
        cmdKali = new javax.swing.JButton();
        cmdBagi = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmd1.setText("1");
        cmd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd1MouseClicked(evt);
            }
        });

        tampil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        cmd2.setText("2");
        cmd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd2MouseClicked(evt);
            }
        });

        cmdSamaDengan.setText("=");
        cmdSamaDengan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdSamaDenganMouseClicked(evt);
            }
        });

        cmdTambah.setText("+");
        cmdTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdTambahMouseClicked(evt);
            }
        });

        cmd3.setText("3");
        cmd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd3MouseClicked(evt);
            }
        });

        cmd4.setText("4");
        cmd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd4MouseClicked(evt);
            }
        });

        cmd5.setText("5");
        cmd5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd5MouseClicked(evt);
            }
        });

        cmd6.setText("6");
        cmd6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd6MouseClicked(evt);
            }
        });

        cmd7.setText("7");
        cmd7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd7MouseClicked(evt);
            }
        });

        cmd8.setText("8");
        cmd8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd8MouseClicked(evt);
            }
        });

        cmd9.setText("9");
        cmd9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd9MouseClicked(evt);
            }
        });

        cmd0.setText("0");
        cmd0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd0MouseClicked(evt);
            }
        });

        cmdKoma.setText(".");
        cmdKoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKomaMouseClicked(evt);
            }
        });

        cmdKurang.setText("-");
        cmdKurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKurangMouseClicked(evt);
            }
        });

        cmdKali.setText("x");
        cmdKali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKaliMouseClicked(evt);
            }
        });

        cmdBagi.setText("/");
        cmdBagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBagiMouseClicked(evt);
            }
        });

        cmdClear.setText("C");
        cmdClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdKoma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd0)
                                .addGap(7, 7, 7)
                                .addComponent(cmdClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdTambah))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmd7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cmd5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdKali))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmd8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdBagi))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tampil))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmd0, cmd1, cmd2, cmd3, cmd4, cmd5, cmd6, cmd7, cmd8, cmd9, cmdBagi, cmdClear, cmdKali, cmdKoma, cmdKurang, cmdSamaDengan, cmdTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd7)
                            .addComponent(cmd8)
                            .addComponent(cmd9)
                            .addComponent(cmdBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd4)
                            .addComponent(cmd5)
                            .addComponent(cmd6)
                            .addComponent(cmdKali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd1)
                            .addComponent(cmd2)
                            .addComponent(cmd3)
                            .addComponent(cmdKurang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd0)
                            .addComponent(cmdKoma)
                            .addComponent(cmdTambah)
                            .addComponent(cmdClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmdSamaDengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmd0, cmd1, cmd2, cmd3, cmd4, cmd5, cmd6, cmd7, cmd8, cmd9, cmdBagi, cmdClear, cmdKali, cmdKoma, cmdKurang, cmdTambah});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd1MouseClicked
        angka += "1";
        tampil.setText("1");
    }//GEN-LAST:event_cmd1MouseClicked

    private void cmd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd2MouseClicked
        angka += "2";
        tampil.setText("2");
    }//GEN-LAST:event_cmd2MouseClicked

    private void cmdTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTambahMouseClicked
        angka1 = Double.parseDouble(angka);
        tampil.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_cmdTambahMouseClicked

    private void cmd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd3MouseClicked
        angka += "3";
        tampil.setText("3");
    }//GEN-LAST:event_cmd3MouseClicked

    private void cmd4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd4MouseClicked
        angka += "4";
        tampil.setText("4");
    }//GEN-LAST:event_cmd4MouseClicked

    private void cmd5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd5MouseClicked
        angka += "5";
        tampil.setText("5");
    }//GEN-LAST:event_cmd5MouseClicked

    private void cmd6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd6MouseClicked
        angka += "6";
        tampil.setText("6");
    }//GEN-LAST:event_cmd6MouseClicked

    private void cmd7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd7MouseClicked
        angka += "7";
        tampil.setText("7");
    }//GEN-LAST:event_cmd7MouseClicked

    private void cmd8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd8MouseClicked
        angka += "8";
        tampil.setText("8");
    }//GEN-LAST:event_cmd8MouseClicked

    private void cmd9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd9MouseClicked
        angka += "9";
        tampil.setText("9");
    }//GEN-LAST:event_cmd9MouseClicked

    private void cmd0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd0MouseClicked
        angka += "0";
        tampil.setText("0");
    }//GEN-LAST:event_cmd0MouseClicked

    private void cmdKomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKomaMouseClicked
        angka += ".";
        tampil.setText(".");
    }//GEN-LAST:event_cmdKomaMouseClicked

    private void cmdKurangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKurangMouseClicked
        angka1 = Double.parseDouble(angka);
        tampil.setText("-");
        angka = "";
        pilih = 2;

    }//GEN-LAST:event_cmdKurangMouseClicked

    private void cmdKaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKaliMouseClicked
        angka1 = Double.parseDouble(angka);
        tampil.setText("*");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_cmdKaliMouseClicked

    private void cmdBagiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBagiMouseClicked
        angka1 = Double.parseDouble(angka);
        tampil.setText("/");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_cmdBagiMouseClicked

    private void cmdClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdClearMouseClicked
        angka1 = 0.0;
        angka2 = 0.0;
        total = 0.0;
        angka = "";
        tampil.setText("");
    }//GEN-LAST:event_cmdClearMouseClicked

    private void cmdSamaDenganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSamaDenganMouseClicked
        switch (pilih) {
            case 1:
                angka2 = Double.parseDouble(angka);
                total = angka1 + angka2;
                angka = Double.toString(total);
                tampil.setText(angka);
                break;

            case 2:
                angka2 = Double.parseDouble(angka);
                total = angka1 - angka2;
                angka = Double.toString(total);
                tampil.setText(angka);
                break;
            case 3:
                angka2 = Double.parseDouble(angka);
                total = angka1 / angka2;
                angka = Double.toString(total);
                tampil.setText(angka);
                break;

            case 4:
                angka2 = Double.parseDouble(angka);
                total = angka1 * angka2;
                angka = Double.toString(total);
                tampil.setText(angka);
                break;
            default:
                break;

        }
    }//GEN-LAST:event_cmdSamaDenganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kalkulator().setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd0;
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JButton cmd3;
    private javax.swing.JButton cmd4;
    private javax.swing.JButton cmd5;
    private javax.swing.JButton cmd6;
    private javax.swing.JButton cmd7;
    private javax.swing.JButton cmd8;
    private javax.swing.JButton cmd9;
    private javax.swing.JButton cmdBagi;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdKali;
    private javax.swing.JButton cmdKoma;
    private javax.swing.JButton cmdKurang;
    private javax.swing.JButton cmdSamaDengan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JFormattedTextField tampil;
    // End of variables declaration//GEN-END:variables

}
